// PREREQUISITE: VOScript.Starter.CapResultParser.Mappings._LungBmk227Mapping
// Source revision 1P-3469-3, exported 2026-09-28 from demo\sales.
// Tier: ai
// Create this in the target tenant BEFORE any generated starter script will compile.
// Do not edit. See prerequisites/README.md.

#region USING NAMESPACES
using System;
using System.Collections.Generic;
using VoiceOver.Common;
using VoiceOver.Extensions;
using VoiceOver.InternalScripts;
#endregion USING NAMESPACES

namespace VOScript.Starter.CapResultParser.Mappings
{
    #region PROPERTYDEF: COMMAND PALETTE PROPERTIES - DO NOT CHANGE CODE IN THIS REGION
    #endregion PROPERTYDEF: COMMAND PALETTE PROPERTIES - DO NOT CHANGE CODE IN THIS REGION

    /// <summary>
    /// AUTO-GENERATED by CAP Template Converter on 2026-07-07T15:02:02.247Z
    /// Template style: flat sibling questions
    /// CAP-side only — labels live in per-vendor overlay files.
    /// Regenerate after CAP protocol updates or recipe changes.
    /// </summary>
    // CLASSDEF: KEEP THE NEXT LINE IN 'public class ScriptName : BaseClassName' FORMAT
    public class _LungBmk227Mapping : ExtensionScript
    {
        public static Dictionary<string, BiomarkerMap> Build()
        {
            return new Dictionary<string, BiomarkerMap>
            {

                // ========================================================
                // PD-L1_22c3
                // ========================================================
                ["PD-L1_22c3"] = new BiomarkerMap
                {
                    Questions = new List<QuestionMap>
                    {
                            new QuestionMap
                            {
                                CKey       = "C978561_100004300",
                                Label      = "PD-L1 22c3 IHC Interpretation",
                                Type       = "categorical",
                                AiProperty = "Status",
                                ValueMap   = new Dictionary<string, string>
                                {
                                    ["Positive"] = "C978562_100004300",
                                    ["Negative"] = "C978563_100004300",
                                    ["Cannot be determined"] = "C978564_100004300"
                                }
                            },
                            new QuestionMap
                            {
                                CKey       = "C978565_100004300",
                                Label      = "Percentage of Tumor Cells with Staining (TPS)",
                                Type       = "numericText",
                                AiProperty = "TPS"
                            }
                    }
                },

                // ========================================================
                // PD-L1_28-8
                // ========================================================
                ["PD-L1_28-8"] = new BiomarkerMap
                {
                    Questions = new List<QuestionMap>
                    {
                            new QuestionMap
                            {
                                CKey       = "C978579_100004300",
                                Label      = "PD-L1 28-8 IHC Interpretation",
                                Type       = "categorical",
                                AiProperty = "Status",
                                ValueMap   = new Dictionary<string, string>
                                {
                                    ["Positive"] = "C978580_100004300",
                                    ["Negative"] = "C978581_100004300",
                                    ["Cannot be determined"] = "C978582_100004300"
                                }
                            }
                    }
                },

                // ========================================================
                // PD-L1_SP142
                // ========================================================
                ["PD-L1_SP142"] = new BiomarkerMap
                {
                    Questions = new List<QuestionMap>
                    {
                            new QuestionMap
                            {
                                CKey       = "C978597_100004300",
                                Label      = "PD-L1 SP142 IHC Interpretation",
                                Type       = "categorical",
                                AiProperty = "Status",
                                ValueMap   = new Dictionary<string, string>
                                {
                                    ["Positive"] = "C978598_100004300",
                                    ["Negative"] = "C978599_100004300",
                                    ["Cannot be determined"] = "C978600_100004300"
                                }
                            }
                    }
                },

                // ========================================================
                // PD-L1_SP263
                // ========================================================
                ["PD-L1_SP263"] = new BiomarkerMap
                {
                    Questions = new List<QuestionMap>
                    {
                            new QuestionMap
                            {
                                CKey       = "C978615_100004300",
                                Label      = "PD-L1 SP263 IHC Interpretation",
                                Type       = "categorical",
                                AiProperty = "Status",
                                ValueMap   = new Dictionary<string, string>
                                {
                                    ["Positive"] = "C978616_100004300",
                                    ["Negative"] = "C978617_100004300",
                                    ["Cannot be determined"] = "C978618_100004300"
                                }
                            }
                    }
                }
            };
        }
    }

#region CLOSEOUT BOILERPLATE
} // close namespace
#endregion CLOSEOUT BOILERPLATE